### ISSUE TITLE
Blank Comments

### ISSUE THREAD

**Issue by fism88** [w7cook/OpenBook#118]
On the main News Feed if you click the Comment button when nothing is typed in, it posts the default "new comment..." text

**Comment by ghost** [comment]
I fixed it. Would you mind doing a quick QA on it for me? I tested it but I just want to make sure. Thanks.

**Comment by fism88** [comment]
Looks good to me!

**Comment by fism88** [comment]
Are you working on Posts too? Same issue with blank posts if you can fix that too

**Comment by ghost** [comment]
Cool, yeah i'll fix posts too. Thanks for noticing the bug.

**Comment by amshali** [comment]
Should I close this issue?

**Comment by amshali** [comment]
never mind
