### ISSUE TITLE
Search on first name and last name doesn't work

### ISSUE THREAD

**Issue by amshali** [w7cook/OpenBook#121]
Hi
We want to be able to search over first name and last name. When I search someone using the first and last name, it doesn't find anything.

**Comment by amdaddeo** [comment]
OK, will work on this.

**Comment by amdaddeo** [comment]
The elastic_search module in play is very new and doesn't implement this feature. I went through the module source code and it looks like in the place where they build the query based on search fields there is comment that says:

```
            // FIXME Currently we search in all fields and ignore searchFields
```

I am going to try to implement this feature in elastic search and then use it in OpenBook. Just wanted to let you know why it was taking so long.

**Comment by amshali** [comment]
Okay. Looking forward to that.

**Comment by amdaddeo** [comment]
This issue is closed.
