### ISSUE TITLE
Redundant comments are shown

### ISSUE THREAD

**Issue by amshali** [w7cook/OpenBook#130]
Create as many as 4 comments on a post. Refresh the page. You will see "n more comments". Click on that and it will show some of the comments redundantly.

**Comment by ghost** [comment]
I think I'm going to remove the hidden comments for now until I can find a better way to display comments. I'll look for some alternatives and get back to you. Thanks.

**Comment by amshali** [comment]
Good, thanks. So what is the consequence of this change?

**Comment by ghost** [comment]
For right now all the comments will show for each post. I want to find a way to only show the last 2 or 3 comments and give the user an option to see all comments so that there aren't any redundancies. Also, the way I had it was causing problems with the like button for each comment.

**Comment by amshali** [comment]
that is cool, but show and hide for all of them would be okay too

**Comment by amshali** [comment]
We definitely need a hide show. 
Thanks
