### ISSUE TITLE
Idea on Avatar

### ISSUE THREAD

**Issue by amshali** [w7cook/OpenBook#142]
How about using Gravatar
https://en.gravatar.com/
for creating user's profile picture? Would be cool I think!

**Comment by jtessler** [comment]
Switching assignment to @laurenyew, given her work on profile pictures. Maybe Gravatar can be one of the options when selecting your profile pic?

**Comment by laurenyew** [comment]
Ok. Ill take a look at it.

**Comment by amshali** [comment]
I like the option idea! Yes, please do a research and see if how we can have it as an option.

**Comment by laurenyew** [comment]
Pull Request #205: Fixed this issue
