### ISSUE TITLE
js sharing between event and checkin

### ISSUE THREAD

**Issue by ProCynic** [w7cook/OpenBook#144]
we've got js for event and checkin that displays a google map.  Is there any reason they can't share js?  I'm trying to pull the event js out into it's own file but that introduced a bug I haven't tracked down yet.
https://github.com/ProCynic/OpenBook/tree/api

**Comment by amshali** [comment]
We should be able to. Let me look at too.

**Comment by ProCynic** [comment]
make sure you look at the code in my repo that I linked because that's the version that I'm probably going to be merging that in soon.
