### ISSUE TITLE
cannot create multiple events

### ISSUE THREAD

**Issue by ProCynic** [w7cook/OpenBook#150]
`PersistenceException occured : org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update`

on line

`event.save();`

**Comment by amshali** [comment]
Needs more testing.

**Comment by ProCynic** [comment]
I did notice that if you delete the existing event it will let you create
another one.  So the problem is trying to create an event when there is
already one in the database.  I'll look at the code that does it later.
-Geoffrey Parker

On Sun, Apr 15, 2012 at 12:02 AM, Amin Shali <
reply@reply.github.com

**Comment by ProCynic** [comment]
looks like it's been fixed
https://github.com/w7cook/OpenBook/commit/e69f63e7622f6d2540258cb6953a57c4784baddd

**Comment by ProCynic** [comment]
yeah, your commit worked.  Didn't notice until after I commented.
