### ISSUE TITLE
Comment position is funny

### ISSUE THREAD

**Issue by amshali** [w7cook/OpenBook#154]
Comment on a post and then refresh the page. The comment position will change

**Comment by ghost** [comment]
I noticed that as well. Do we want a hanging indentation for the comments list? I thought it looked nicer. I'll try to make them all uniform. Thanks

**Comment by amshali** [comment]
I don't like the hanging indentation. But it's your call. Please test throughly.

**Comment by ghost** [comment]
fixed.
