### ISSUE TITLE
About me edit does not save

### ISSUE THREAD

**Issue by amshali** [w7cook/OpenBook#163]
After editing and hitting the save button, it does not save the updated values.

**Comment by amshali** [comment]
@fism88 , @aluu317 
This issue is still there. What are we gonna do about it?

**Comment by fism88** [comment]
Have some questions, will be there at 3pm in your office hours today

**Comment by ghost** [comment]
Birthday saving functionality is still not there is it? when I tried to save a birthday yesterday for Jeff I got this error:

Execution error occured in template /app/views/Users/profile.html. Exception raised was NullPointerException : null.

156:               <td class="data">${profile.anniversary.format("MM/dd/yyyy")}</td>

**Comment by fism88** [comment]
I fixed that with my last pull request. It should be working. Have you pulled the latest stuff?

**Comment by fism88** [comment]
Let me know if it's broken again, I'll fix it up for you

**Comment by fism88** [comment]
okay fixed it, it was working for Bob, but not Jeff
