### ISSUE TITLE
Like/unlike disappears

### ISSUE THREAD

**Issue by ghost** [w7cook/OpenBook#182]
When you write a comment on a post and then refresh the page, it looks like the Like/Unlike button disappears. There's now a small empty box below the "delete" button.

**Comment by ghost** [comment]
I think I have a hidden comment list displaying the same comment and that's why the like button is disappearing. I'll fix it. thank you for bringing it to my attention.

**Comment by ghost** [comment]
I made the changes. Feel free to test and verify my solution. I'll let you close the issue when you're satisfied with the results. Thanks.

**Comment by amshali** [comment]
LGTM
