### ISSUE TITLE
A bunch of pages do not work do to an open form tag

### ISSUE THREAD

**Issue by ellio** [w7cook/OpenBook#185]
Pages such as account.html, setProfilePhotoPage.html, and I'm sure others do not work because there is an open {#form tag.  Traced it back to commit c50c7f5c9645b3b38f8be49ca3c866caa9b7769b by vados.

**Comment by amshali** [comment]
I fixed account.html, setProfilePhotoPage.html. What others?

**Comment by ellio** [comment]
Let me do a quick run through on the files he changed to see if any others
were actually affected - it's possible that these were the only two.

On Wed, Apr 18, 2012 at 12:43 PM, Amin Shali <
reply@reply.github.com

**Comment by ellio** [comment]
friendRequests.html, edit_basic.html are the only I could find.

**Comment by amshali** [comment]
Fixed.
