### ISSUE TITLE
Order of comemnts are wrong after refresh

### ISSUE THREAD

**Issue by amshali** [w7cook/OpenBook#187]
Try this
create 5 comments with a number representing the content of each one
1
2
3
4
5
. 
Now refresh and click to show all comments. 
Ordering is kinda messed up.

**Comment by amshali** [comment]
Please note that I changed the way comments and post metadata are shown now.

**Comment by ghost** [comment]
I fixed the ordering but there is still an issue with the formatting for the individual comments. The right edge of the comments list is a bit jagged. When you hit like it changes the width of the individual comment. It wasn't noticeable when the background was white but now the background is grey and it stands out. Any suggestions to fix it?

**Comment by amshali** [comment]
how's it now?

**Comment by ghost** [comment]
it looks good. i'll close the issue.
