### ISSUE TITLE
Wrong poster for profile page comments

### ISSUE THREAD

**Issue by ghost** [w7cook/OpenBook#188]
This issue was mentioned briefly in class before, but it's still there. When you click on another user's name and go to their 'profile' page, if you post a comment it will be as that friend's name instead of the current user.

**Comment by ProCynic** [comment]
This is because the comments api is wrong.  The comment creation method in controllers/Comments.java should not take a user id, it should have the logged in user be the author of the comment.

**Comment by ProCynic** [comment]
After #219 replacing js with import of /public/javascripts/post.js should fix this.

**Comment by amshali** [comment]
close?

**Comment by ProCynic** [comment]
not yet.
