### ISSUE TITLE
Mix of User.about(id) and Application.about(id) calls

### ISSUE THREAD

**Issue by ghost** [w7cook/OpenBook#189]
The links when you click on users' names are mixed all around the app between two different "about" pages: Users/about.html and Application/about.html. (For example, clicking on anyone's name within the news feed  leads to Users/about.html and within the Events pages it leads to Application/about.html)

I guess we decided in class to use Users/about.html?

**Comment by amshali** [comment]
Yes.

**Comment by ghost** [comment]
On that note, since Users/about.html is going to be the one showing up after a search for a user, there needs to be a Friend Request option on that page.

**Comment by amshali** [comment]
Exactly. Agreed.

**Comment by ProCynic** [comment]
I believe that Victor said that he would be converting all of this to Timeline.  Might ask him about it.

**Comment by ProCynic** [comment]
I removed Application/about.html
