### ISSUE TITLE
Signup email confirmation timeline save problem

### ISSUE THREAD

**Issue by laurenyew** [w7cook/OpenBook#203]
When doing a signup, after the email confirmation is set, clicking on the link for the email confirmation results in an error in the timeline.save()

**Comment by ellio** [comment]
I tested this all before submitting, something else must have broken it - I'll look into it.

**Comment by ellio** [comment]
This is probably related to the timeline code being added to the User constructor- have you tested making a new user, vados?

**Comment by amshali** [comment]
I think this is fixed. Lauren please pull and try and confirm.

**Comment by t3hmrman** [comment]
Hey is this resolved, or should I take a look at it...

I essentially make a new timeline object with the new created user and save
it to the db... that's all
On Apr 21, 2012 12:09 PM, "Amin Shali" <
reply@reply.github.com>
wrote:

**Comment by amshali** [comment]
I think it is resolved.
