### ISSUE TITLE
About me edit

### ISSUE THREAD

**Issue by amshali** [w7cook/OpenBook#213]
No edit button works.

**Comment by ProCynic** [comment]
I'd be willing to fix it in the bootstrap version.
-Geoffrey Parker

On Sun, Apr 22, 2012 at 9:16 PM, Amin Shali <
reply@reply.github.com

**Comment by fism88** [comment]
Okay that works, thanks! I'm not sure what the problem is yet in the current code. It's working fine for me with nothing changed.

**Comment by amshali** [comment]
Have you committed all the necessary files? It should work for me too, but it doesn't.
