### ISSUE TITLE
comment.html tag has unclosed div

### ISSUE THREAD

**Issue by seanpcoyle** [w7cook/OpenBook#252]
Line 2 of /app/views/tags/comment.html has an unclosed div.  I'd close it myself, but closing it properly alters the layout of the comments and I wasn't sure how exactly the comments team wants the comments styled.

**Comment by ProCynic** [comment]
That looks like my fault.  I'll check it out when I get a minute.

**Comment by ProCynic** [comment]
fixed in #254
