### ISSUE TITLE
Bootstrap defaultPhoto variables reset upon recompilation

### ISSUE THREAD

**Issue by ellio** [w7cook/OpenBook#260]
Try this:

1) Start play - make sure not to save any java files once its started
2) Create a new user
3) Confirm the signup for the user

Everything should work fine.

Now do this:

1) Edit some java file - adding a comment or somesuch should be enough.
2)  Create a new user
3) Confirm the signup for the user

The following error occurs: "this.profilePhoto = Photo.findById(Bootstrap.defaultProfilePhotoID);"
This is because it sees Bootstrap.defaultProfilePhotoID as null now.

**Comment by amshali** [comment]
@laurenyew , @jtessler 
Please have a look at this. I kinda suspect it might be lack of correct tagging on User and Profile relation.

**Comment by laurenyew** [comment]
Ok. The basic reason for using the profile picture ID was to try to avoid hard coding. I think that now that we have photo objects for the profile picture, I can take out the use of those static variables. I'll take a look
