### ISSUE TITLE
Error when deleting profile photo

### ISSUE THREAD

**Issue by jtessler** [w7cook/OpenBook#270]
Steps to recreate the error:
1. Upload photo
2. Set it as the profile photo
3. Go to "My Photos"
4. Delete the photo

The error:

```
Execution exception
PersistenceException occured : org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update

In /app/controllers/Photos.java (around line 99)
...
```

However, if you do the same thing with background photo, it deletes gracefully and the background turns white.

**Comment by ProCynic** [comment]
Probably something to do with the link between Profile and the photo.  Make sure you set the users profile pic back to default when they delete their current one.

**EDIT**
Make sure you switch the photos _before_ the delete.

**Comment by t3hmrman** [comment]
Since jackie told me today that essentially all persistence errors come
from model disruptions, maybe it has something to do with the `@required`
annotation on profile pic? It is required right?
On May 2, 2012 5:12 PM, "Joe Tessler" <
reply@reply.github.com>
wrote:

**Comment by ProCynic** [comment]
yup, we want required.  see the above comment.

**Comment by t3hmrman** [comment]
Yeah I get that we want it, but maybe we need to disable the delete option
by checking if the picture to be deleted is the profile picture
On May 2, 2012 5:17 PM, "Geoffrey Parker" <
reply@reply.github.com>
wrote:

**Comment by ProCynic** [comment]
Why would we not let people delete their own profile pics?

**Comment by t3hmrman** [comment]
Sorry I misspoke (mistyped) - change the action from an actual delete to
reset to default's THEN delete. Deleting the picture in place might be the
problem, if other things are dependent
On May 2, 2012 5:20 PM, "Geoffrey Parker" <
reply@reply.github.com>
wrote:

**Comment by ProCynic** [comment]
yeah, that's what I said.
https://github.com/w7cook/OpenBook/issues/270#issuecomment-5473986

**Comment by t3hmrman** [comment]
Oh yeah, agreed then, didn't see the edit, just read joe's msg
On May 2, 2012 5:38 PM, "Geoffrey Parker" <
reply@reply.github.com>
wrote:
