### ISSUE TITLE
Markdown breaks Messages

### ISSUE THREAD

**Issue by jackietsay** [w7cook/OpenBook#279]
Add a message with content "test", it shows up as "java.io.FileNotFoundException: /home/jackie/cs378/OpenBook/test (Is a directory)"

Caused by markdown() in app/views/Messages/inbox.html:34

**Comment by astolarz** [comment]
That error is not showing up anymore (I assume do to some changes you have made since filing this). There was a typo in Messages/inbox.html that caused the page to look all screwy ("dif" instead of "div").
